import type { Deal } from "@/types";

export const deals: Deal[] = [
  {
    id: "deal-001",
    title: "Acme Cloud CRM Expansion",
    companyId: "company-001",
    contactId: "contact-001",
    value: 42000,
    stage: "proposal",
    probability: 65,
    expectedCloseDate: "2026-06-20",
  },
  {
    id: "deal-002",
    title: "Northstar Labs Startup Plan",
    companyId: "company-002",
    contactId: "contact-002",
    value: 18000,
    stage: "qualified",
    probability: 45,
    expectedCloseDate: "2026-06-28",
  },
  {
    id: "deal-003",
    title: "BrightPath Agency Team Seats",
    companyId: "company-003",
    contactId: "contact-003",
    value: 26000,
    stage: "negotiation",
    probability: 75,
    expectedCloseDate: "2026-07-05",
  },
  {
    id: "deal-004",
    title: "Vertex Systems Enterprise Rollout",
    companyId: "company-004",
    contactId: "contact-004",
    value: 96000,
    stage: "lead",
    probability: 25,
    expectedCloseDate: "2026-07-15",
  },
  {
    id: "deal-005",
    title: "Orbit Finance Growth CRM",
    companyId: "company-005",
    contactId: "contact-005",
    value: 54000,
    stage: "won",
    probability: 100,
    expectedCloseDate: "2026-05-30",
  },
];
