import type { Lead } from "@/types";

export const leads: Lead[] = [
  {
    id: "lead-001",
    name: "Daniel Brooks",
    email: "daniel@scalehub.io",
    company: "ScaleHub",
    source: "Website",
    status: "new",
    assignedTo: "user-003",
    createdAt: "2026-05-01",
  },
  {
    id: "lead-002",
    name: "Grace Lee",
    email: "grace@growthlane.co",
    company: "GrowthLane",
    source: "LinkedIn",
    status: "contacted",
    assignedTo: "user-004",
    createdAt: "2026-05-04",
  },
  {
    id: "lead-003",
    name: "Henry Adams",
    email: "henry@revpilot.com",
    company: "RevPilot",
    source: "Referral",
    status: "qualified",
    assignedTo: "user-003",
    createdAt: "2026-05-08",
  },
  {
    id: "lead-004",
    name: "Nora Scott",
    email: "nora@marketgrid.io",
    company: "MarketGrid",
    source: "Webinar",
    status: "proposal",
    assignedTo: "user-004",
    createdAt: "2026-05-11",
  },
  {
    id: "lead-005",
    name: "Lucas Miller",
    email: "lucas@taskly.app",
    company: "Taskly",
    source: "Website",
    status: "converted",
    assignedTo: "user-005",
    createdAt: "2026-05-15",
  },
  {
    id: "lead-006",
    name: "Zoe Carter",
    email: "zoe@bluepeak.ai",
    company: "BluePeak AI",
    source: "Cold Email",
    status: "lost",
    assignedTo: "user-003",
    createdAt: "2026-05-18",
  },
];
